// Code generated by "stringer -type Method -output methodlines.go"; DO NOT EDIT.

package rtsp

import "strconv"

const _Method_name = "DESCRIBEANNOUNCEGET_PARAMETEROPTIONSPAUSEPLAYRECORDREDIRECTSETUPSET_PARAMETERTEARDOWN"

var _Method_index = [...]uint8{0, 8, 16, 29, 36, 41, 45, 51, 59, 64, 77, 85}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
