// Code generated by "stringer -output statuslines.go -type Status -linecomment"; DO NOT EDIT.

package rtsp

import "strconv"

const (
	_Status_name_0 = "100 Continue"
	_Status_name_1 = "200 OK201 Created"
	_Status_name_2 = "250 Low on Storage Space"
	_Status_name_3 = "300 Multiple Choices301 Moved Permanently302 Moved Temporarily303 See Other304 Not Modified305 Use Proxy"
	_Status_name_4 = "400 Bad Request401 Unauthorized402 Payment Required403 Forbidden404 Not Found405 Method Not Allowed406 Not Acceptable407 Proxy Authentication Required408 Request Time-out409 UNDEFINED410 Gone411 Length Required412 Precondition Failed413 Request Entity Too Large414 Request-URI Too Large415 Unsupported Media Type"
	_Status_name_5 = "451 Parameter Not Understood452 Conference Not Found453 Not Enough Bandwidth454 Session Not Found455 Method Not Valid in This State456 Header Field Not Valid for Resource457 Invalid Range458 Parameter Is Read-Only459 Aggregate operation not allowed460 Only aggregate operation allowed461 Unsupported transport462 Destination unreachable"
	_Status_name_6 = "500 Internal Server Error501 Not Implemented502 Bad Gateway503 Service Unavailable504 Gateway Time-out505 RTSP Version not supported"
	_Status_name_7 = "551 Option not supported"
)

var (
	_Status_index_1 = [...]uint8{0, 6, 17}
	_Status_index_3 = [...]uint8{0, 20, 41, 62, 75, 91, 104}
	_Status_index_4 = [...]uint16{0, 15, 31, 51, 64, 77, 99, 117, 150, 170, 183, 191, 210, 233, 261, 286, 312}
	_Status_index_5 = [...]uint16{0, 28, 52, 76, 97, 131, 170, 187, 213, 248, 284, 309, 336}
	_Status_index_6 = [...]uint8{0, 25, 44, 59, 82, 102, 132}
)

func (i Status) String() string {
	switch {
	case i == 100:
		return _Status_name_0
	case 200 <= i && i <= 201:
		i -= 200
		return _Status_name_1[_Status_index_1[i]:_Status_index_1[i+1]]
	case i == 250:
		return _Status_name_2
	case 300 <= i && i <= 305:
		i -= 300
		return _Status_name_3[_Status_index_3[i]:_Status_index_3[i+1]]
	case 400 <= i && i <= 415:
		i -= 400
		return _Status_name_4[_Status_index_4[i]:_Status_index_4[i+1]]
	case 451 <= i && i <= 462:
		i -= 451
		return _Status_name_5[_Status_index_5[i]:_Status_index_5[i+1]]
	case 500 <= i && i <= 505:
		i -= 500
		return _Status_name_6[_Status_index_6[i]:_Status_index_6[i+1]]
	case i == 551:
		return _Status_name_7
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
